### ISSUE TITLE
How should model `Game` be implemented?

### ISSUE THREAD

**Issue by Xiaohong-Deng** [Xiaohong-Deng/mooqita-icccg#3]
Anyone is against the idea of having a model called `Game`?

What your idea on it? Like what attributes it should have. What associations it should have? One association is clear. That is, `has_many: users`. What about others?

I raise this issue because it's necessary to have a `Game` model at an early stage. When a user starts a game, a corresponding object should be created. Or should it? Should we create a such object until the game actually is active instead of being waiting others to join?

That also affects the `state` attribute a `Game` object has. A game should be in one of **waiting**, **alive**, **dead** states or just **alive**, **dead**?

**Comment by Rojo** [comment]
@Xiaohong-Deng @jwald1 

Based on this idea, the description from the article and the work Jacob has done, I assembled this ER diagram to help us have a better vision of the possible data interactions for the game.

![iccg er](https://user-images.githubusercontent.com/92138/29642277-83d2e2c8-882d-11e7-8158-26e5b96878e6.png)

The `Game` state can be represented by an _enum integer_. Here is a link to an article that shows how to use this kind of data representation with _ActiveRecord_: [https://www.justinweiss.com/articles/creating-easy-readable-attributes-with-activerecord-enums/](https://www.justinweiss.com/articles/creating-easy-readable-attributes-with-activerecord-enums/)

This is the base file for the ER diagram: [ICCG ER.mdj.zip](https://github.com/Xiaohong-Deng/mooqita-icccg/files/1247299/ICCG.ER.mdj.zip). It can be easily edited with [StarUML](http://staruml.io/).

**Comment by Xiaohong-Deng** [comment]
@Rojo Great work. Really valuable info. @jwald1 should take a look at this. The major relationships are clear.

**Comment by jwald1** [comment]
I'm `Game` in `join-game-action-cable` I use `enum`.  The players' roles can also be done with `enum`

**Comment by jwald1** [comment]
Here is my attempt for the DB design.
![ICCG ERD.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/598a35d4a585de001a0271d2/125516c66e82c728ace21e0d46c1b7b904c2a69bababf301b44fff9e2c4533317346f67228dce671be137a59570a46aa41585c4dfda88c2aa0b32e6c981e5ab38532022d8c6853beb2901cbe0bbb258b4c83b5bc8a4ec8eb3423f5c6.png)

**Comment by Rojo** [comment]
@jwald1 I think I read some discussion on the Slack channel, but can you explain again what are the advantages of having the `games` and `game_players` normalization over only having the `game` entity with included references to the players?

**Comment by jwald1** [comment]
@Rojo I'll try to explain it after the weekend.

**Comment by jwald1** [comment]
In general, we establish a many-to-many relationship through a joint table. One of the reasons for this is because we don't want to add an individual column for each reference. In our case, since we know before hand that we only need three references, one might say "Why not add them directly to the table?", But what would happen if the client would request to have a 'listener' added to the game? We would then need to add a column to the game.

Additionally, when it comes to scoring since we don't have a join table, we will need to add a one-to-one relationship to a scores table and create columns for each player type. Also, to me, a score belongs to a player, not to the game.

Once we decide to go for a joint table, we can opt either for a simple join (HABTM) or for a rich join (HMT). Following is a list of articles on this topic http://cobwwweb.com/why-i-dont-use-has-and-belongs-to-many-in-rails, http://blog.flatironschool.com/why-you-dont-need-has-and-belongs-to-many/

In our case, having GamePlayer as a separate entity is important. One reason for this is ActionCable connection identification.

Hope this helps

**Comment by Xiaohong-Deng** [comment]
@jwald1 why game_players has many users? why it has many scores?
